name: first-actions
on:
  push:
    branches:
      - main
jobs: 
  first-job:
    runs-on: 	ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install  
      - name: Run tests
        run: npm test
      - name: Print greeting
        run: |
          echo "Hellow World!"
          mkdir pastaTeste
          ls -la
      - name: Print goodbye
        run: echo "Done - bye"
