name: first-actions
on:
  push:
    branches:
      - main
jobs: 
  first-job:
    runs-on: 	ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hellow World!"
          mkdir pastaTeste
          ls -la
      - name: Print goodbye
        run: echo "Done - bye"
